=== baslenvm/198371_Lab_and_exam/LAB_04/Patcharaphong.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://gear.kku.ac.th/Patcharaphong"
    xmlns:tns="http://gear.kku.ac.th/Patcharaphong"
    elementFormDefault="qualified">
    <xsd:element name="profile">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="about">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="name">
                                <xsd:complexType>
                                    <xsd:attribute name="prefix" type="xsd:string"/>
                                    <xsd:attribute name="firstname" type="xsd:string"/>
                                    <xsd:attribute name="lastname" type="xsd:string"/>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="sex"/>
                            <xsd:element name="birthday"/>
                            <xsd:element name="hobbies"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="background">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="skill" minOccurs="0" maxOccurs="unbounded"/>
                            <xsd:element name="education" minOccurs="0" maxOccurs="unbounded" type="tns:education"></xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="contact">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="hometown" type="xsd:string"/>
                            <xsd:element name="address" type="xsd:string"/>
                            <xsd:element name="postcode" type="xsd:string"></xsd:element>
                            <xsd:element name="email" type="xsd:string"/>
                            <xsd:element name="website">
                                <xsd:complexType>
                                    <xsd:attribute name="facebook" type="xsd:string"/>
                                    <xsd:attribute name="googleplus" type="xsd:string"/>
                                    <xsd:attribute name="twitter" type="xsd:string"/>
                                    <xsd:attribute name="linkedin" type="xsd:string"/>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="phone" type="xsd:string"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:complexType name="education" mixed="true">
        <xsd:sequence>
            <xsd:element name="school">
                <xsd:complexType>
                    <xsd:simpleContent>
                        <xsd:extension base="xsd:string">
                            <xsd:attribute name="graduation" type="xsd:string"/>
                        </xsd:extension>
                    </xsd:simpleContent>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="faculty" type="xsd:string" minOccurs="0"/>
            <xsd:element name="address" type="xsd:string" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== baslenvm/198371_Lab_and_exam/5530405861-Patcharaphong-lab04/Patcharaphong.xml
<?xml version="1.0" encoding="UTF-8"?>
<profile xmlns="http://gear.kku.ac.th/Patcharaphong"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:schemaLocation="http://gear.kku.ac.th/Patcharaphong Patcharaphong.xsd">
    <about>
        <name prefix='Mr.' firstname='Patcharaphong' lastname='Batdee'/>
        <sex>male</sex>
        <birthday>10/13/1993</birthday>
        <hobbies>Play computer</hobbies>
    </about>
    <background>
        <skill />
        <education>
            1.ประถม
            <school graduation='2005'>Banbua School</school>
            <address>Sakon Nakhon</address>
        </education>
        <education>
            2.มัธยม
            <school graduation='2011'>Sakolraj School</school>
            <address>Sakon Nakhon</address>
        </education>
        <education>
            3.มหาวิทยาลัย
            <school graduation=''>Khon Kaen University</school>
            <faculty>Engineering</faculty>
            <address>Khon Kaen</address>
        </education>
    </background>
    <contact>
        <hometown>Sakon Nakhon</hometown>
        <address>34/13, Swang, Phanna Nikhon, Sakon Nakhon</address>
        <postcode>47130</postcode>
        <email>Patcharaphong.batdee@kkumail.com</email>
        <website facebook='https://www.facebook.com/Baslenvm'
                 googleplus='https://plus.google.com/109989934828415341352'
                 twitter='https://twitter.com/baslenvm'
                 linkedin='http://th.linkedin.com/pub/patcharaphong-batdee/88/467/437'/>
        <phone>088-3361656</phone>
    </contact>
</profile>
