=== baslenvm/198371_Lab_and_exam/LAB_04/quotes.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://gear.kku.ac.th/Patcharaphong"
            xmlns:tns="http://gear.kku.ac.th/Patcharaphong"
            elementFormDefault="qualified">
    <xsd:complexType name="quotesTypes" mixed="true">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="quote" type="tns:qoutetype" maxOccurs="unbounded" minOccurs="0"/>
            <xsd:element name="br" type="tns:brType"/>
        </xsd:choice>
    </xsd:complexType>
    <xsd:complexType name="brType"/>
    <xsd:complexType name="qoutetype" mixed="true">
        <xsd:sequence>
            <xsd:element name="words" maxOccurs="1"/>
            <xsd:element name="author" type="tns:authorType" maxOccurs="1"></xsd:element>
            <xsd:element name="date" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="referred_by" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="authorType" mixed="true">
        <xsd:attribute name="aid" type="xsd:string"/>
    </xsd:complexType>
    <xsd:element name="quotes" type="tns:quotesTypes"/>
</xsd:schema>

=== baslenvm/198371_Lab_and_exam/LAB_04/quotes.xml
<?xml version="1.0"?>
<quotes xmlns="http://gear.kku.ac.th/Patcharaphong"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://gear.kku.ac.th/Patcharaphong quotes.xsd">
    These are a few famous quotes:
    <quote>
        <words>We cannot do great things, only small things with great 				love.</words>written by
        <author aid='a01'>Mother Teresa</author>
        <date>December 05, 1930</date>
        <referred_by>India News</referred_by>
        <referred_by>Loving and Caring People</referred_by>
    </quote>
    <br />
    <quote>
        <words>Learn as if you would live forever. Live as if you would 				die tomorrow.</words>written by
        <author aid='a02'>Ghandi</author>
    </quote>
</quotes>
