=== baslenvm/198371_Lab_and_exam/quiz1/books.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://gear.kku.ac.th/Patcharaphong"
    xmlns:tns="http://gear.kku.ac.th/Patcharaphong"
    elementFormDefault="qualified">
    <xsd:element name="catalog">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="book" type="tns:book" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:complexType name="book">
        <xsd:sequence>
            <xsd:element name="title">
                <xsd:complexType mixed="true">
                    <xsd:attribute name="lang" type="xsd:string" default="english"/>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="price"/>
            <xsd:element name="date" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="publish_year">
                <xsd:complexType mixed="true">
                    <xsd:attribute name="year" type="xsd:string"/>
                    <xsd:attribute name="type" type="xsd:string"/>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="description" type="tns:description" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="description" mixed="true">
        <xsd:sequence>
            <xsd:element name="thai"/>
            <xsd:element name="br"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== baslenvm/198371_Lab_and_exam/quiz1/books.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="books.xsl"?>
<catalog xmlns="http://gear.kku.ac.th/Patcharaphong"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:schemaLocation="http://gear.kku.ac.th/Patcharaphong books.xsd">
    <book id="bk101">
        <title lang="thai">ประชุมโครงโลกนิติ</title>
        <price>40</price>
        <publish_year type="Buffhist valender">2384</publish_year>
    </book>
    <book id="bk102">
        <title>What I Knew When I Was 20</title>
        <price>18.32</price>
        <date>2013-10-22</date>
        <publish_year>2009</publish_year>
        <description>Opportunities are abundunt,but you need to identify problems
            <thai>นวัตกรรมมากมายสามรถออกมาจากตัวเรา ได้หากเราไม่ยีดติดกับความรู้เติมๆ พื้นที่ปลอดภัย</thai>
            <br />
        </description>
    </book>
</catalog>
