=== baslenvm/198371_Lab_and_exam/MIDTERM/teacher.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://gear.kku.ac.th"
    xmlns:tns="http://gear.kku.ac.th"
    elementFormDefault="qualified">
    <xsd:element name="teachers">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="teacher" minOccurs="0" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="name"/>
                            <xsd:element name="classes">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="class" maxOccurs="unbounded" minOccurs="0">
                                            <xsd:complexType mixed="true">
                                                <xsd:attribute name="id" type="xsd:string"/>
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="papers" minOccurs="0">
                                <xsd:complexType mixed="true">
                                    <xsd:sequence>
                                        <xsd:element name="paper" minOccurs="0" maxOccurs="unbounded">
                                            <xsd:complexType>
                                                <xsd:attribute name="name" type="xsd:string"/>
                                                <xsd:attribute name="isi" type="xsd:string"/>
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                        <xsd:attribute name="id" type="xsd:string"/>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== baslenvm/198371_Lab_and_exam/MIDTERM/teacher.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="teacher.xsl"?>
<teachers xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
          xmlns='http://gear.kku.ac.th'
          xsi:schemaLocation='http://gear.kku.ac.th teacher.xsd'>
    <teacher id="4830409876-5">
        <name>Somchai Rakchart<nickname>Chai</nickname></name>
        <classes>
            <class id="198371">XML and Web Services</class>
            <class id="198290">Computer Engineering Workshop</class>
        </classes>
    </teacher>
    <teacher id="46301234-5">
        <name>Somying Ruknailuang</name>
        <classes>
            <class id="198371">XML and Web Services</class>
            <class id="198372">Web Programming</class>
            <class id="198130">Advanced Computer Programming</class>
        </classes>
        <papers>These are my recent papers
            <paper name="A Review and Comparison of Rule Languages" isi="no"/>
            <paper name="A Mobile App and an API for Essential and Useful Thai Herbs Search"
                    isi="yes"/>
        </papers>
    </teacher>
</teachers>
